### ISSUE TITLE
User can RENAME a project

### ISSUE THREAD

**Issue by EmilyRosina** [EmilyRosina/user-story-builder#2]
# Reason
To allow **the user** to **rename** their **active project**.

---
#### Prerequisites
- User must have at least one project
- User must be on the project for which they want to rename

#### Tasks
- [x] clicking option button opens options modal
- [x] **options modal allows for rename of project** - save and cancel
- [x] validate if name change is ok
- [x] **action** - update localStorage, commit mutation
- [x] **mutation** - update state
- [x] **notify user** - change successful
- [x] reflect new name in UI
