### ISSUE TITLE
Optimise project options

### ISSUE THREAD

**Issue by EmilyRosina** [EmilyRosina/user-story-builder#5]
# Reason
Allows **the user** to **access and implement** more **project options**.
- Add
- Rename
- Delete
- Delete all 
- Switch

---
#### Prerequisites
- User must have at least one project
- User must be on the project for which they want to rename
- User must have at least two projects in order to switch project

#### Tasks
- [x] clicking option button reveals options popover
- [x] popover styling
- [x] **options popover sections**
  - [x] Add project
  - [x] Rename project
  - [x] Delete project
  - [x] Delete all projects
  - [x] Switch project
- [x] refactor **rename code** to suit new method
- [x] refactor **delete code** to suit new method
- [x] pull out dialogs into own components
- [x] **validation working**
  - [x] Add project
  - [x] Rename project
- [x] **all options completed**
  - [x] Add project
  - [x] Rename project
  - [x] Delete project
  - [x] Delete all projects
  - [x] Switch project
- [x] styling tweaks to message confirm boxes (fit better on mobiles)
